package main

import (
	"fmt"
	"os"
	"path/filepath"

	gofpdf "github.com/jung-kurt/gofpdf"
)

const outputPath = "testdata/mock-signing-document.pdf"

func main() {
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		panic(fmt.Errorf("create output directory: %w", err))
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle("PDF Signing Test Document", true)
	pdf.SetAuthor("Akkarapon Phikulsri Testing Certificated", true)
	pdf.SetCreator("pdf-signature-usecase", true)
	pdf.SetSubject("Mock PDF for digital-signature testing", true)
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	pdf.SetFont("Arial", "B", 20)
	pdf.CellFormat(0, 12, "PDF Signing Test Document", "", 1, "C", false, 0, "")
	pdf.Ln(4)

	pdf.SetFont("Arial", "", 12)
	pdf.MultiCell(0, 7, "This document is generated locally for testing PDF signing with the mock certificate named Akkarapon Phikulsri Testing Certificated.", "", "L", false)
	pdf.Ln(8)

	pdf.SetDrawColor(80, 80, 80)
	pdf.SetFillColor(245, 247, 250)
	pdf.Rect(20, 75, 170, 42, "DF")
	pdf.SetFont("Arial", "B", 12)
	pdf.SetXY(28, 84)
	pdf.Cell(45, 8, "Signing subject:")
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(110, 8, "Akkarapon Phikulsri Testing Certificated")
	pdf.SetXY(28, 96)
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(45, 8, "Document purpose:")
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(110, 8, "Mock input for digital-signature tests")

	pdf.SetY(140)
	pdf.SetFont("Arial", "I", 10)
	pdf.CellFormat(0, 7, "Generated by github.com/refactorroom/gofpdf", "", 1, "C", false, 0, "")

	if err := pdf.OutputFileAndClose(outputPath); err != nil {
		panic(fmt.Errorf("write %s: %w", outputPath, err))
	}

	fmt.Println(outputPath)
}
